name: 'linux'
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/linux.yml'
      - '.github/release.yml'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  
jobs:
  linux:
    runs-on: ${{ vars.LINUX }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    name: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO }}
        check-latest: true
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE }}
        cache: 'npm'
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ vars.ZIG }}
        cache: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_APITOKEN }}        
    - run: go run .
      env:
        CGO_ENABLED: 0
        PLATFORM: ${{ matrix.platform }}
