name: 'linux'
on:
  push:
    paths:
      - '.github/workflows/linux.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  
jobs:
  linux:
    runs-on: ${{ vars.LINUX }}
    name: ${{ vars.LINUX }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE }}
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ vars.ZIG }}
    - run: |
        go env
        go run .
      env:
        CGO_ENABLED: 0
        IMAGE: ${{ vars.LINUX }}
