name: 'linux_64'
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:  
jobs:
  linux_64:
    runs-on: ${{ vars.OS }}
    name: ${{ vars.OS }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE }}
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ vars.ZIG }}
    - name: running tool
      env:
        OS_IMAGE: ${{ vars.OS }}
      run: |
        echo "OS name: ${{ inputs.os_image }}"
        CGO_ENABLED=0 go run .



