name: 'macos'
on:
  push:
    paths:
      - '.github/workflows/macos.yml'
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:  
jobs:
  macos:
    runs-on: ${{ vars.MACOS }}
    name: ${{ vars.MACOS }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE }}
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ vars.ZIG }}
    - run: |
        echo "IMAGE: $IMAGE"
        CGO_ENABLED=0 go run .
      env:
        IMAGE: ${{ vars.MACOS }}
