name: 'windows'
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/windows.yml'
      - '.github/release.yml'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  
jobs:
  windows:
    strategy:
      matrix:
        osimage:
          - windows-2022
    runs-on: ${{ matrix.osimage }}
    name: ${{ matrix.osimage }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO }}
        check-latest: true
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE }}
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ vars.ZIG }}
        cache: true
    - name: Set up QEMU
      if: matrix.osimage == 'windows-2022'
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker buildx
      if: matrix.osimage == 'windows-2022'
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      if: matrix.osimage == 'windows-2022'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_APITOKEN }} 
    - run: go run .
      env:
        CGO_ENABLED: 0
        OS_IMAGE: ${{ matrix.osimage }}
